openapi: 3.0.1
info:
  title: NTTData - Cuentas
  description: Cuentas
  termsOfService: 'http://localhost/terms.html'
  contact:
    name: Edwin Bucay
    url: 'https://www.linkedin.com/in/geovannybucay/'
    email: win_geovanny88@hotmail.com
  license:
    name: NTTData
    url: 'http://localhost/license.html'
  version: v1
paths:
  /clientes/consulta-clientes:
    get:
      tags:
        - Cliente
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteResponseMsDtoResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
  /clientes/consulta-cliente:
    get:
      tags:
        - Cliente
      parameters:
        - name: identificacion
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteResponseMsDtoResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
  /clientes/crear-cliente:
    post:
      tags:
        - Cliente
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClienteRequest'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteResponseMsDtoResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
  /clientes/actualizar-cliente:
    put:
      tags:
        - Cliente
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClienteRequest'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteRequestMsDtoResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
  /clientes/eliminar-cliente:
    delete:
      tags:
        - Cliente
      parameters:
        - name: identificacion
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClienteResponseMsDtoResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
  /cuentas/consulta-cuenta:
    get:
      tags:
        - Cuenta
      parameters:
        - name: cuenta
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CuentaResponseMsDtoResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
  /clientes/consulta-cuentas:
    get:
      tags:
        - Cuenta
      parameters:
        - name: identificacion
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CuentaResponseMsDtoResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
  /clientes/crear-cuenta:
    post:
      tags:
        - Cuenta
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CuentaRequest'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CuentaResponseMsDtoResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
  /clientes/actualizar-cuenta:
    put:
      tags:
        - Cuenta
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CuentaRequest'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CuentaRequestMsDtoResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
  /clientes/eliminar-cuenta:
    delete:
      tags:
        - Cuenta
      parameters:
        - name: identificacion
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CuentaResponseMsDtoResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
  /movimientos/consulta-movimientos-fecha:
    get:
      tags:
        - Movimiento
      parameters:
        - name: fechaInicio
          in: header
          required: true
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovimientoResponseMsDtoResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
  /movimientos/consulta-movimientos-cuenta:
    get:
      tags:
        - Movimiento
      parameters:
        - name: numeroCuenta
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovimientoResponseMsDtoResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
  /clientes/crear-movimiento:
    post:
      tags:
        - Movimiento
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovimientoRequest'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovimientoResponseMsDtoResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
  /clientes/actualizar-movimiento:
    put:
      tags:
        - Movimiento
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MovimientoResponse'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovimientoResponseMsDtoResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
  /clientes/eliminar-movimiento:
    delete:
      tags:
        - Movimiento
      parameters:
        - name: numeroCuenta
          in: header
          required: true
          schema:
            type: string
        - name: idMovimiento
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovimientoResponseMsDtoResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
        '500':
          description: Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MsDtoResponseError'
components:
  schemas:
    ClienteRequest:
      type: object
      properties:
        nombre:
          type: string
          nullable: true
        identificacion:
          type: string
          nullable: true
        direccion:
          type: string
          nullable: true
        telefono:
          type: string
          nullable: true
        genero:
          type: string
          nullable: true
        edad:
          type: integer
          format: int32
          nullable: true
        contrasenia:
          type: string
          nullable: true
        estado:
          type: boolean
          nullable: true
      additionalProperties: false
    ClienteRequestMsDtoResponse:
      type: object
      properties:
        traceid:
          type: string
          nullable: true
        data:
          $ref: '#/components/schemas/ClienteRequest'
      additionalProperties: false
    ClienteResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        nombre:
          type: string
          nullable: true
        identificacion:
          type: string
          nullable: true
        direccion:
          type: string
          nullable: true
        telefono:
          type: string
          nullable: true
        genero:
          type: string
          nullable: true
        edad:
          type: integer
          format: int32
          nullable: true
        contrasenia:
          type: string
          nullable: true
        estado:
          type: boolean
          nullable: true
      additionalProperties: false
    ClienteResponseMsDtoResponse:
      type: object
      properties:
        traceid:
          type: string
          nullable: true
        data:
          $ref: '#/components/schemas/ClienteResponse'
      additionalProperties: false
    CuentaRequest:
      type: object
      properties:
        numeroCuenta:
          type: string
          nullable: true
        tipoCuenta:
          type: string
          nullable: true
        saldoInicial:
          type: number
          format: double
          nullable: true
        estado:
          type: boolean
          nullable: true
        nombreCliente:
          type: string
          nullable: true
      additionalProperties: false
    CuentaRequestMsDtoResponse:
      type: object
      properties:
        traceid:
          type: string
          nullable: true
        data:
          $ref: '#/components/schemas/CuentaRequest'
      additionalProperties: false
    CuentaResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        numeroCuenta:
          type: string
          nullable: true
        tipoCuenta:
          type: string
          nullable: true
        saldoInicial:
          type: number
          format: double
          nullable: true
        estado:
          type: boolean
          nullable: true
        nombreCliente:
          type: string
          nullable: true
      additionalProperties: false
    CuentaResponseMsDtoResponse:
      type: object
      properties:
        traceid:
          type: string
          nullable: true
        data:
          $ref: '#/components/schemas/CuentaResponse'
      additionalProperties: false
    MovimientoRequest:
      type: object
      properties:
        id:
          type: integer
          format: int32
        numeroCuenta:
          type: string
          nullable: true
        tipoCuenta:
          type: string
          nullable: true
        saldoInicial:
          type: number
          format: double
        estado:
          type: string
          nullable: true
        descripcionMovimiento:
          type: string
          nullable: true
      additionalProperties: false
    MovimientoResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
        fechaMovimento:
          type: string
          format: date-time
        nombreCliente:
          type: string
          nullable: true
        numeroCuenta:
          type: string
          nullable: true
        tipoCuenta:
          type: string
          nullable: true
        saldoInicial:
          type: number
          format: double
        estado:
          type: string
          nullable: true
        movimiento:
          type: number
          format: double
        saldoDisponible:
          type: number
          format: double
      additionalProperties: false
    MovimientoResponseMsDtoResponse:
      type: object
      properties:
        traceid:
          type: string
          nullable: true
        data:
          $ref: '#/components/schemas/MovimientoResponse'
      additionalProperties: false
    MsDtoError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
          nullable: true
      additionalProperties: false
    MsDtoResponseError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        traceid:
          type: string
          nullable: true
        message:
          type: string
          nullable: true
        errors:
          type: array
          items:
            $ref: '#/components/schemas/MsDtoError'
          nullable: true
      additionalProperties: false
